FROM ubuntu:latest

RUN apt update && apt upgrade -y && \
    \
    # terraform のインストール手順
    apt install -y unzip zip git && \
    \
    #tfenvのインストール
    git clone https://github.com/tfutils/tfenv.git ~/.tfenv

ENV PATH="/root/.tfenv/bin:$PATH"

    #tfenv install latestで使用するcurlコマンドをインストール
RUN apt install -y curl && \
    tfenv install latest && \
    tfenv use latest

COPY ./tf/ /home/

WORKDIR /home

RUN chmod +x ./start.sh

#CMD ["./start.sh"]


    # ansible のインストール手順
ENV DEBIAN_FRONTEND=noninteractive

RUN echo "Etc/UTC" > /etc/timezone && \
    apt install -y tzdata && \
    dpkg-reconfigure -f noninteractive tzdata

RUN apt update && \
    apt install software-properties-common -y && \
    apt-add-repository --yes --update ppa:ansible/ansible && \
    apt install ansible -y